#ifndef FORWARD_H
#define FORWARD_H

#include <QtCore>

QT_FORWARD_DECLARE_CLASS(MainWindow);
QT_FORWARD_DECLARE_CLASS(Station);
QT_FORWARD_DECLARE_CLASS(Storage);
QT_FORWARD_DECLARE_CLASS(Server);
QT_FORWARD_DECLARE_CLASS(Dome);
QT_FORWARD_DECLARE_CLASS(Universe);
QT_FORWARD_DECLARE_CLASS(Log);
QT_FORWARD_DECLARE_CLASS(Request);
QT_FORWARD_DECLARE_CLASS(Command);

#endif // FORWARD_H
