#ifndef FORWARD_H
#define FORWARD_H

#include <QtCore>

QT_FORWARD_DECLARE_CLASS(MainWindow);
QT_FORWARD_DECLARE_CLASS(Station);
QT_FORWARD_DECLARE_CLASS(Server);
QT_FORWARD_DECLARE_CLASS(Universe);
QT_FORWARD_DECLARE_CLASS(Log);

#endif // FORWARD_H
